recast-hep/recast-atlas

setup.py
src/recastatlas/config.py
src/recastatlas/subcommands/catalogue.py

this PR adds support for a new type of configuration file, an "index" file that allows to add multiple analyses
in one go to the catalogue.
This is useful for the organization of meta-analyses, like the pMSSM scan.
cc @matthewfeickert @danikam

index file support

---

.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/lint.yml

As part of fixing the CI across a series of PRs start in this one by seperating out the CI into 3 distinct workflows: Python testing, linting, and Docker tests.
These workflows will all fail at the moment, which is expected as this PR just splits out failing workflows. The Python testing workflow will be fixed in PR #43 which will be rebased on top of this PR. Other PRs for fixing linting and Docker building can follow.
**Suggested squash and merge commit message**
```
* Split the CI workflows into seperated Python testing, linting, and Docker building workflows
- These workflows currently fail but that is expected
```

ci: Split out workflows

---

.github/workflows/ci.yml
README.md
setup.py

Requires PR #44 to go in first.
---
The CI is failing as the default database cache that the base images have are out of sync with the package lists for Ubuntu and also because of conflicts with `yadage[viz]`. Running `apt-get update` first will retrieve the latest package lists and ensure that `apt-get install` will proceed. Also manually install the components of `yadage[viz]`. Additionally update the build status badge to reflect the state of GitHub Actions on `master`.
[![CI](https://github.com/recast-hep/recast-atlas/actions/workflows/ci.yml/badge.svg)](https://github.com/recast-hep/recast-atlas/actions/workflows/ci.yml?query=branch%3Amaster)

ci: Fix Python tests CI workflow

---

.flake8
.github/workflows/lint.yml
pyproject.toml
setup.py
src/recastatlas/backends/__init__.py
src/recastatlas/backends/docker.py
src/recastatlas/backends/kubernetes.py
src/recastatlas/backends/local.py
src/recastatlas/backends/reana.py
src/recastatlas/config.py
src/recastatlas/exceptions.py
src/recastatlas/subcommands/auth.py
src/recastatlas/subcommands/catalogue.py
src/recastatlas/subcommands/run.py
src/recastatlas/subcommands/software.py
src/recastatlas/subcommands/testing.py
src/recastatlas/testing.py
tests/test_cli.py

Requires PR #43 to go in first.
---
Apply linting with Black and flake8 such that the Lint CI workflow passes.
```
* Use flake8 over pyflakes
- Add .flake8 to configure flake8
* Apply Black to codebase
* Fix flake8 errors and warnings
- E402: module level import not at top of file
- E713: test for membership should be 'not in'
- E722: do not use bare 'except'
- W291: trailing whitespace
```

chore: Apply linting with Black and flake8

---

.github/workflows/docker.yml

Fix the Docker build CI
~~To run `recast run testing/busyboxtest --backend docker` ensure that the environmental variable `RECASE_DOCKER_IMAGE` is set to the value of the image that was just build in CI. Additionally, running recast locally requires that it is both installed and that `graphviz` is installed too.~~
To run `recast run testing/busyboxtest --backend docker` in GitHub Actions CI requires some additional work to get the Docker in Docker setup. For the time being, be content with the build tests of the Dockerfile and local testing elsewhere.
c.f. Issue #50
The equivalent to running
```console
recast run testing/busyboxtest --backend local
```
is still being run in 
https://github.com/recast-hep/recast-atlas/blob/4eba02ea6678f253a9bb578cf70385d01b581f32/.github/workflows/ci.yml#L4 …

ci: Fix Docker build workflow

---

.bumpversion.cfg
setup.cfg
setup.py

Resolves #40
Requires PR #46 to go in first
```
* Migrate all PyPI metadata and declarative setup information to setup.cfg
* Have bumpversion update version information in setup.cfg
* Add requirement of Python 3.6 or later for install
* Set approximate lower bounds on recast-atlas core dependencies
* Add PyPI classifier metadata and project urls
```

build: Migrate setup spec and metadata from `setup.py` to `setup.cfg`

---

src/recastatlas/backends/reana.py

this appeared in the pMSSM RECAST. `os.path.basename` on a string with a trailing `/` trips up, so this PR fixes this via `rstrip`

fix: strip path

---

setup.py

Requires PR #46 to go in first.
---
`reana-client` `v0.7.5` has a dependency on `cwltool==1.0.20191022103248` which apparently has conflicts with `setuptools` `v58.0.0` and later, presumably from the [breaking changes](https://github.com/pypa/setuptools/blob/main/CHANGES.rst#breaking-changes) that were introduced of
> Removed support for 2to3 during builds. Projects should port to a unified codebase or pin to an older version of Setuptools using PEP 518 build-requires.
The release of `reana-client` `v0.8.0` will fix this and the `setuptools` restriction will be able to be removed.
c.f. reanahub/reana-client#558

build: Require setuptools<58.0.0 for reana extra

---

MANIFEST.in

Applies https://github.com/scikit-hep/pyhf/pull/1449
```
* Use `prune **` to remove all files from the sdist
- c.f. https://packaging.python.org/guides/using-manifest-in/#manifest-in-commands
- "Setuptools also has undocumented support for ** matching zero or more characters including forward slash, backslash, and colon."
* Manually include all "default" files for a sdist in MANIFEST.in
- c.f. https://packaging.python.org/guides/using-manifest-in/#how-files-are-included-in-an-sdist
```

build: Revise MANIFEST.in strategy to properly use prune

---

.github/workflows/deploy.yml
.github/workflows/publish-package.yml

Add GHA based workflow to release a sdist and wheel to:
- TestPyPI on tags
- PyPI on GitHub releases
Locally on `master` run:
```console
$ git checkout master && git pull # verify that you're on master and synced with GitHub
$ bump2version <part> # bump the version and create a commit and tag
$ git push origin master --tags # push the commit and the tag to GitHub, causing TestPyPI to publish
```
- Got to TestPyPI (https://test.pypi.org/project/recast-atlas/) to look if the release looks okay
- Then on GitHub:
1. Go to releases: https://github.com/recast-hep/recast-atlas/releases
2. Click "Draft a new release"
3. On the new page enter the tag you just pushed (e.g. `v0.1.0`) in the "Tag version" box and the "Release title" box (to make it easy unless you really want to get descriptive)
4. …

ci: Add workflow to deploy to distributions to TestPyPI and PyPI

---

docs/maintainer-notes.md

* Resolves #42 
* Resolves #59 
Adds notes for maintainers on how to make a release.

docs: Add release instructions for maintainers

---

.github/workflows/ci.yml

Run the CI with the Kubernetes and REANA dependencies additionally installed to determine the behavior in a "full" environment. This requires that `setuptools<58.0.0` given https://github.com/reanahub/reana-client/issues/558 and there is not a `v0.8.0` `reana-client` release yet.
```
* Install 'kubernetes' and 'reana' extras in CI before running tests
* Restrict setuptools<58.0.0 to allow for installation of reana-client
- c.f. https://github.com/reanahub/reana-client/issues/558
```

ci: Add Kubernetes and REANA dependencies to CI

---

src/recastatlas/backends/__init__.py
src/recastatlas/subcommands/backends.py

Resolves #75
If a backend is unloadable during `recast backends ls --check`, instead of raising a `KeyError`, instead catch the `KeyError`, raise `recastatlas.exceptions.BackendNotAvailableException`, and report 'NOT AVAILABLE' for the STATUS.
**Example:**
```console
$ docker run --rm -it python:3.8 /bin/bash
root@d6fcd8105311:/# python -m venv venv && . venv/bin/activate
(venv) root@d6fcd8105311:/# python -m pip --quiet install --upgrade pip "setuptools<58.0.0" wheel six
(venv) root@d6fcd8105311:/# git clone https://github.com/recast-hep/recast-atlas.git && cd recast-atlas && git checkout origin/feat/note-module-misisng-over-fail -b feat/note-module-misisng-over-fail
(venv) root@d6fcd8105311:/recast-atlas# python -m pip install .
(venv) root@d6fcd8105311:/recast-atlas# recast backends ls …
```

feat: Report 'NOT AVAILABLE' if backend unloaded

---

src/recastatlas/subcommands/auth.py

Attempting to login to a Docker registry using `docker login -p` will generate the warning message from Docker
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin
```
to avoid this use `printf` and pipes to send the user password to docker login resulting in the command
```
printf "${RECAST_REGISTRY_PASSWORD}" | docker login --username "${RECAST_REGISTRY_USERNAME}" --password-stdin "${RECAST_REGISTRY_HOST}"
```
being used by `recast auth setup`. Additionally use f-strings to simplify formatting and update the warning message users see RE: environmental variables.
```bash
eval "$(recast auth setup -a ${RECAST_AUTH_USERNAME} -a ${RECAST_AUTH_PASSWORD} -a ${RECAST_AUTH_TOKEN} -a default)"
```
```
You password is stored in the environment variables …
```

fix: Login to docker registry with `--password-stdin` to avoid warning

---

.github/workflows/ci.yml
docker/Dockerfile
setup.py

[`reana-client` `v0.8.0`](https://github.com/reanahub/reana-client/releases/tag/0.8.0) is out.
More details also in the release blog https://blog.reana.io/posts/2021/release-0.8.0/
```
* Update reana-client lower bound to v0.8.0 for setuptools stability
- c.f. https://github.com/reanahub/reana-client/issues/558
* Remove setuptools<58.0.0 cap
```

build: Update reana-client to v0.8.0+

---

setup.cfg
setup.py

```
* Set lower bound of adage to v0.10.1
* Set lower bound of yadage-schemas to v0.10.6
* Set lower bound of packtivity to v0.14.23
* Relies on reana-commons v0.8.1 allowing for patch releases of yadage
org libraries to float.
- https://github.com/reanahub/reana-commons/issues/322
- https://github.com/reanahub/reana-commons/pull/323
```

build: Set lower bounds for adage, yadage-schemas, and packtivity

---

setup.cfg

```
* Remove six from install_requires as yadage-schemas v0.10.7 now
defines six>=1.4.0 as as requirement.
* Set lower bound on yadage-schemas of v0.10.7.
* Reverts PR #77
```

build: Remove explicit six dependency

---

.github/workflows/ci.yml
.github/workflows/publish-package.yml
setup.cfg

```
* Add Python 3.9 and Python 3.10 to testing in CI
* Use default options for `python -m build`
* Add support for Python 3.9 and Python 3.10 to PyPI classifiers metadata
```

ci: Add testing for Python 3.9 and Python 3.10

---

.github/workflows/head-of-dependencies.yml

Resolves #97
Nightly test release candidates and yadage org dependencies for 'local' extra.
The HEAD of `yadage` test job is currently failing because of https://github.com/yadage/yadage/issues/116 (and so is expected).
```
* Nightly test release candidates and yadage org dependencies for 'local'
extra.
- adage, packtivity, and yadage
```

ci: Add HEAD of dependencies workflow

---

.github/workflows/bump-version.yml
.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/head-of-dependencies.yml
.github/workflows/lint.yml
.github/workflows/publish-package.yml

```
* Drop Python 3.6 from the testing matrix.
* Update actions/checkout and actions/setup-python
GitHub Actions to latest releases.
```

ci: Drop Python 3.6 tests

---

setup.cfg

* Drop support for Python 3.6 and required Python 3.7+ for use.

build: Require Python 3.7+

---

src/recastatlas/data/catalogue/atlas_atlas_conf_2018_041.yml
src/recastatlas/data/catalogue/busyboxtest.yml
src/recastatlas/data/catalogue/examples_checkmate1.yml
src/recastatlas/data/catalogue/examples_checkmate2.yml
src/recastatlas/data/catalogue/examples_rome.yml

* Explicitly state the branch name for the `<username/repo[@branch]>[:subpath]` pattern.
c.f. https://github.com/reanahub/reana-demo-atlas-recast/issues/43.

fix: Make target branch of toplevel explicit in examples

---

.github/workflows/ci.yml
setup.cfg

* Drop support for Python 3.7 and require Python 3.8+ for use.

build: Require Python 3.8+

---

.github/workflows/ci.yml
.github/workflows/head-of-dependencies.yml
setup.cfg

* Add Python 3.11 to testing in CI.
* Add Python 3.11 to PyPI trove classifiers metadata.
* Use Python 3.11 for CI workflows.

ci: Add Python 3.11 to testing

---

.github/workflows/ci.yml
.github/workflows/head-of-dependencies.yml

* As unused, don't need to add additional package solve constraints during tests.

ci: Remove 'kubernetes' extra from testing

---

README.md

* Add install example commands for the 'local' and 'reana' extras when using the respective backends.

docs: Add extra install examples for backends

---

deploy/deploy_lxplus9.sh

Partially addresses Issue #124 
Can't yet set `PACKTIVITY_CONTAINER_RUNTIME` to `apptainer` as that requires a `packtivity` update.
```
* Add APPTAINER_CACHEDIR as lxplus9 uses apptainer.
* Set SINGULARITY_CACHEDIR to be APPTAINER_CACHEDIR.
* Add notice to loging to private cotnainer registiries before use.
- Avoid issues with login problems later.
```

chore: Add apptainer variables to lxplus9 deployment

---

README.md

* The `recast submit` command supports the reana backend, not `recast run`.

fix: Use 'recast submit' for reana backend

---

src/recastatlas/backends/docker.py
src/recastatlas/config.py

Resolves #128 
* If the environment variable `DOCKER_DEFAULT_PLATFORM` exists use it to set the `--platform` option for `docker run`. This is required to be able to run on other platform than the native host's with emulation.
- c.f. https://docs.docker.com/engine/reference/commandline/cli/#environment-variables

feat: Set docker platform from DOCKER_DEFAULT_PLATFORM env variable

---

.github/workflows/bump-version.yml
.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/head-of-dependencies.yml
.github/workflows/lint.yml
.github/workflows/publish-package.yml

```
* Update GitHub Actions:
- actions/checkout to v4
- actions/setup-python to v5
- upload-artifact to v4
- download-artifact to v4
- pypa/gh-action-pypi-publis to v1.8.11
- docker/setup-qemu-action to v3
- docker/setup-buildx-action to v3
- docker/login-action to v3
- docker/build-push-action to v5
```

ci: Update GitHub Actions versions

---

.github/workflows/docker.yml

* Add the 'platforms' argument to the docker/build-push-action GitHub Action and pass the platform names to enable build for both amd64 and arm64 architectures. This will enable Apple silicon machines to run the Docker images without emulation which will significantly improve runtime performance.

ci: Enable multiplatform builds for amd64 and arm64

---

setup.cfg
src/recastatlas/config.py
src/recastatlas/subcommands/auth.py
src/recastatlas/subcommands/catalogue.py

Addresses part of Issue #137 
```
* Add importlib-resources as an install dependency for Python 3.8 as Python 3.12 deprecates
and removes pkg_resources.
* Replace use of pkg_resources.resource_filename with importlib.resources.files
for Python 3.9+ and importlib_resources.files for Python 3.8.
* Apply isort.
```

fix: Use importlib-resources over deprecated pkg_resources

---

docker/Dockerfile

* Speed up the Dockerfile build by using uv to install all Python dependencies.
* Set PATH to include a default virtual environment and install Python dependencies inside the virtual environment at /usr/local/venv.

chore: Use uv during Dockerfile build

---

.github/workflows/bump-version.yml
.github/workflows/ci.yml
.github/workflows/head-of-dependencies.yml
.github/workflows/lint.yml

* Add Python 3.12 to testing matrix in CI.
* Use Python 3.12 or '3.x' for the default Python in CI.

ci: Add Python 3.12 to CI

---

.github/workflows/ci.yml

* Python 3.12 installs with uv are currently unreliable, so fall back to using pip.
- c.f. https://github.com/astral-sh/uv/issues/4333

ci: Use pip install for Python 3.12

---

.github/workflows/ci.yml

* To avoid backtracking issues (https://github.com/astral-sh/uv/issues/4333), place a lower bound on `snakemake` to bounce `uv` into the correct resolution path.
Thanks to @zanieb for this fix. :+1:

ci: Use snakemake lower bound to force uv solve

---

README.md

Provides a workaround for Issue https://github.com/recast-hep/recast-atlas/issues/51 and https://github.com/recast-hep/recast-atlas/issues/118.
* To have the local backend run correctly it requires the Linux containers being executed to be root. To ensure this, set the `PACKTIVITY_DOCKER_CMD_MOD` environmental variable to `"-u root"`.
* Add environmental setup instructions for the `reana` backend example.
* Add `coolname` in install example and use it for the local backend tag.
* Add additional explanations to both the `local` and `reana` backend examples.
```
* To have the local backend run correctly it requires the Linux containers being
executed to be root. To ensure this, set the 'PACKTIVITY_DOCKER_CMD_MOD'
environment variable to "-u root".
* Add environmental setup instructions for …
```

docs: Add additional run requirements to 'local' and 'reana' backend examples

---

.github/workflows/ci.yml
.github/workflows/head-of-dependencies.yml
.github/workflows/publish-package.yml

* As recast-atlas is hatchling based now, setuptools isn't required.

ci: Remove setuptools install

---

.flake8
.github/workflows/lint.yml
.pre-commit-config.yaml
README.md
pyproject.toml
src/recastatlas/backends/__init__.py
src/recastatlas/backends/docker.py
src/recastatlas/backends/kubernetes.py
src/recastatlas/backends/local.py
src/recastatlas/backends/reana.py
src/recastatlas/cli.py
src/recastatlas/config.py
src/recastatlas/exceptions.py
src/recastatlas/resultsextraction.py
src/recastatlas/subcommands/auth.py
src/recastatlas/subcommands/backends.py
src/recastatlas/subcommands/catalogue.py
src/recastatlas/subcommands/ci.py
src/recastatlas/subcommands/run.py
src/recastatlas/subcommands/software.py
src/recastatlas/subcommands/testing.py
src/recastatlas/testing.py
tests/test_cli.py

```
* Use Ruff for linting and formatting.
- Use Ruff in pre-commit over pyupgrade, black, and flake8.
- Enable additional linting in pyproject.toml ruff tool section.
- Remove .flake8 and black config section of pyproject.toml.
- Use Ruff in lint workflow.
* Disable some recommended Ruff lints.
- c.f. https://learn.scientific-python.org/development/guides/style/#ruff
* Apply ruff formatting to source code.
* Add Ruff formatting badge to README.
```

chore: Use Ruff for linting and formatting

---

.git-blame-ignore-revs

Add a git blame ignore-revs file to automatically ignore commits listed in it from the blame view on GitHub. Include in it style changes added by pre-commit hooks which touch multiple files.
To ignore the commits in the .git-blame-ignore-revs when running `git blame` locally run: `git blame --ignore-revs-file .git-blame-ignore-revs`.
c.f.:
* https://git-scm.com/docs/git-blame#Documentation/git-blame.txt---ignore-revs-fileltfilegt
* https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view

chore: Add .git-blame-ignore-revs to ignore style in blame view

---

.bumpversion.cfg

* Remove setup.cfg from bump2version.
```
* Remove setup.cfg from bump2version.
* Amends PR https://github.com/recast-hep/recast-atlas/pull/145.
```

chore: Remove mentions of setuptools build tools

---

src/recastatlas/subcommands/catalogue.py

* As setuptools is not the build backend there should be no reliance on setuptools or distutils for use. This exchanges the deprecated distutils.dir_util.copy_tree for shutil.copytree as recast-atlas is Python 3.8+.
* Note that as distutils is also deprecated, if this was not done then setuptools._distutils.dir_util.copy_tree would need to be used.

fix: Use shutil.copytree over distutils

---

src/recastatlas/subcommands/catalogue.py

* Add dirs_exist_ok=True to allow the copying operation to continue if it encounters existing directories.
- c.f. https://docs.python.org/3.12/library/shutil.html#shutil.copytree
- dirs_exist_ok was added in Python 3.8.
* Amends PR #155.
```
* Add dirs_exist_ok=True to allow the copying operation to continue if
it encounters existing directories.
- c.f. https://docs.python.org/3.12/library/shutil.html#shutil.copytree
- dirs_exist_ok was added in Python 3.8.
* Amends PR https://github.com/recast-hep/recast-atlas/pull/155.
```

fix: Allow for shutil.copytree to have existing dirs

---

.github/workflows/publish-package.yml

Resolves #154 
* TestPyPI distributions are not important enough to have duplicate human readable attestations.

ci: Publish GitHub attestations only for PyPI builds
